### ISSUE TITLE
ebb-tide to graphmarks.co

### ISSUE THREAD

**Issue by ebb-tide** [heatherbooker/graphmarks#17]
@heatherbooker could you change the link on the github <> code page to www.graphmarks.co from ebb-tide.co/graphmarks?

**Comment by heatherbooker** [comment]
done! can it be made so that when you click the link, the url doesn't change to ebb-tide? just behind the scenes?

**Comment by ebb-tide** [comment]
not yet. soon.
-d

**Comment by ebb-tide** [comment]
annnnd done.
