### ISSUE TITLE
broken site !

### ISSUE THREAD

**Issue by ebb-tide** [heatherbooker/graphmarks#3]
the site seems to be generating an error, also there is no error view to render there should probably be one.

**Comment by ebb-tide** [comment]
@heatherbooker:  annnnd done!- this happened because the process manager that kept graphmarks alive even when we changed it was looking for "heatherbooker/bookmarks-visualizer/bin/www" to run, and we changed the folder name to graphmarks. but you had said that graphmarks is not running for you locally as well. could you try running npm start from the home dir, that should work.

**Comment by heatherbooker** [comment]
oh.. yeah `npm start` works to load the landing page, but none of the links work from there! like it shows this https://puu.sh/ulGxc/0f616706cc.png when i click the "see an awesome demo" link.

**Comment by ebb-tide** [comment]
oh, ok- this is a known bug. hah.

This is because things work differently on the server vs. the local host.
the 'base url' is different. I would have to make express context aware to
fix this, but I don't think it's worth it atm?
localhost:3002/graphmarks/vis.html doesn't work, but
localhost:3002/vis.html should work.
:)
-d

**Comment by heatherbooker** [comment]
mmmm! oh that makes sense good call. but i think we dont want it to be /graphmarks right because then it would be graphmarks.co/graphmarks/vis.html

(reopening issue so it shows up on issue list :) )

**Comment by ebb-tide** [comment]
it's already not though, eb

**Comment by ebb-tide** [comment]
it's not actually- graphmarks.co -> ebb-tide.co/graphmarks/
and all links go to ebb-tide.co/graphmarks/etc.html I'm closing this..
