### ISSUE TITLE
what is this? description for page and chrome ext. 

### ISSUE THREAD

**Issue by ebb-tide** [heatherbooker/graphmarks#4]

**Comment by ebb-tide** [comment]
https://docs.google.com/document/d/1gQAn0ptlgNS1R0L956kqGqAzmYQYKGVA9k7OatAPEo0/edit @heatherbooker

**Comment by heatherbooker** [comment]
awesome! ill put it with the modal when i can test it. :)

**Comment by ebb-tide** [comment]
do edit it however you wish !

**Comment by ebb-tide** [comment]
back at chu @heatherbooker  !

**Comment by ebb-tide** [comment]
modal it up when you feel like it, @heatherbooker !

**Comment by heatherbooker** [comment]
modal added in #18
